/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NouveauVolontaire;

import Containers.Adresse;
import Containers.Identite;
import Containers.Residence;
import Containers.Volontaire;
import GUI.Panels.Main;
import Network.NetworkClient;
import PacketCom.PacketCom;
import States.States;
import Wizard.Wizard_Nouveau;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Greenlamp
 */
public class M_NouveauVolontaireP1 extends javax.swing.JPanel {

    /**
     * Creates new form M_NouveauVolontaire1
     */
    Main parent = null;
    NetworkClient socket = null;
    Volontaire volontaire = null;
    String matricule = null;

    public M_NouveauVolontaireP1(Main parent, NetworkClient socket) {
        initComponents();
        this.socket = socket;
        this.parent = parent;
        ComboBoxAnnee();
        matricule = parent.getMatricule();
        volontaire = parent.getVolontaire();
        if(volontaire.getIdentite() != null){
            fillChampIdentite();
        }
        if(volontaire.getAdresse() != null){
            fillChampAdresse();
        }
        if(volontaire.getResidence() != null){
            fillChampResidence();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Gnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Gprenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Ghomme = new javax.swing.JRadioButton();
        Gfemme = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        GnomFille = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Gjour = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Gmois = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        Gannee = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        Gemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Grue = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Gnumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Gboite = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        GcodePostal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Gville = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Gpays = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        GpaysResidence = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        GvilleResidence = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        GnumeroResidence = new javax.swing.JTextField();
        GboiteResidence = new javax.swing.JTextField();
        GcodePostalResidence = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        GrueResidence = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Bterminer = new javax.swing.JButton();
        Bannuler = new javax.swing.JButton();
        Bsuivant = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nouveau volontaire");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("Nom");

        jLabel3.setText("Prénom");

        jLabel4.setText("Sexe");

        Ghomme.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(Ghomme);
        Ghomme.setSelected(true);
        Ghomme.setText("H");
        Ghomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GfemmeActionPerformed(evt);
            }
        });

        Gfemme.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(Gfemme);
        Gfemme.setText("F");
        Gfemme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GfemmeActionPerformed(evt);
            }
        });

        jLabel5.setText("Nom d'épouse");

        GnomFille.setEnabled(false);

        jLabel6.setText("Date de naissance");

        Gjour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel7.setText("/");

        Gmois.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel8.setText("/");

        jLabel9.setText("Adresse E-Mail");

        jLabel10.setText("Rue");

        jLabel11.setText("Numéro");

        jLabel12.setText("Boite");

        jLabel13.setText("Code Postal");

        jLabel14.setText("Ville");

        jLabel15.setText("Pays");

        Gpays.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Belgique", "Afghanistan", "Afrique du Sud", "Albanie", "Algérie", "Allemagne", "Andorre", "Angola", "Anguilla", "Antarctique", "Antigua-et-Barbuda", "Antilles néerlandaises", "Arabie saoudite", "Argentine", "Arménie", "Aruba", "Australie", "Autriche", "Azerbaïdjan", "Bénin", "Bahamas", "Bahreïn", "Bangladesh", "Barbade", "Belau", "Belize", "Bermudes", "Bhoutan", "Biélorussie", "Birmanie", "Bolivie", "Bosnie-Herzégovine", "Botswana", "Brésil", "Brunei", "Bulgarie", "Burkina Faso", "Burundi", "Côte d'Ivoire", "Cambodge", "Cameroun", "Canada", "Cap-Vert", "Chili", "Chine", "Chypre", "Colombie", "Comores", "Congo", "Corée du Nord", "Corée du Sud", "Costa Rica", "Croatie", "Cuba", "Danemark", "Djibouti", "Dominique", "Égypte", "Émirats arabes unis", "Équateur", "Érythrée", "Estonie", "États-Unis", "Éthiopie", "Finlande", "Géorgie", "Gabon", "Gambie", "Ghana", "Gibraltar", "Grèce", "Grenade", "Groenland", "Guadeloupe", "Guam", "Guatemala", "Guinée", "Guinée équatoriale", "Guinée-Bissao", "Guyana", "Guyane française", "Haïti", "Honduras", "Hong Kong", "Hongrie", "Ile Bouvet", "Ile Christmas", "Ile Norfolk", "Iles Cayman", "Iles Cook", "Iles Féroé", "Iles Falkland", "Iles Fidji", "Iles Géorgie du Sud et Sandwich du Sud", "Iles Heard et McDonald", "Iles Marshall", "Iles Pitcairn", "Iles Salomon", "Iles Svalbard et Jan Mayen", "Iles Turks-et-Caicos", "Iles Vierges américaines", "Iles Vierges britanniques", "Iles des Cocos (Keeling)", "Iles mineures éloignées des États-Unis", "Inde", "Indonésie", "Iran", "Iraq", "Irlande", "Islande", "Israël", "Italie", "Jamaïque", "Japon", "Jordanie", "Kazakhstan", "Kenya", "Kirghizistan", "Kiribati", "Koweït", "Laos", "Lesotho", "Lettonie", "Liban", "Liberia", "Libye", "Liechtenstein", "Lituanie", "Luxembourg", "Macao", "Madagascar", "Malaisie", "Malawi", "Maldives", "Mali", "Malte", "Mariannes du Nord", "Maroc", "Martinique", "Maurice", "Mauritanie", "Mayotte", "Mexique", "Micronésie", "Moldavie", "Monaco", "Mongolie", "Montserrat", "Mozambique", "Népal", "Namibie", "Nauru", "Nicaragua", "Niger", "Nigeria", "Nioué", "Norvège", "Nouvelle-Calédonie", "Nouvelle-Zélande", "Oman", "Ouganda", "Ouzbékistan", "Pérou", "Pakistan", "Panama", "Papouasie-Nouvelle-Guinée", "Paraguay", "Pays-Bas", "Philippines", "Pologne", "Polynésie française", "Porto Rico", "Portugal", "Qatar", "République centrafricaine", "République démocratique du Congo", "République dominicaine", "République tchèque", "Réunion", "Roumanie", "Royaume-Uni", "Russie", "Rwanda", "Sénégal", "Sahara occidental", "Saint-Christophe-et-Niévès", "Saint-Marin", "Saint-Pierre-et-Miquelon", "Saint-Siège", "Saint-Vincent-et-les-Grenadines", "Sainte-Hélène", "Sainte-Lucie", "Salvador", "Samoa", "Samoa américaines", "Sao Tomé-et-Principe", "Seychelles", "Sierra Leone", "Singapour", "Slovénie", "Slovaquie", "Somalie", "Soudan", "Sri Lanka", "Suède", "Suisse", "Suriname", "Swaziland", "Syrie", "Taïwan", "Tadjikistan", "Tanzanie", "Tchad", "Terres australes françaises", "Territoire britannique de l'Océan Indien", "Thaïlande", "Timor Oriental", "Togo", "Tokélaou", "Tonga", "Trinité-et-Tobago", "Tunisie", "Turkménistan", "Turquie", "Tuvalu", "Ukraine", "Uruguay", "Vanuatu", "Venezuela", "Viêt Nam", "Wallis-et-Futuna", "Yémen", "Yougoslavie", "Zambie", "Zimbabwe" }));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Adresse");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Gnom)
                        .addComponent(Gprenom)
                        .addComponent(GnomFille)
                        .addComponent(Gemail)
                        .addComponent(Grue)
                        .addComponent(Gpays, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Gville)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Ghomme)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Gfemme))
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Gjour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Gmois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Gannee, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(Gnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Gboite, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel12)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GcodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ghomme)
                    .addComponent(Gfemme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GnomFille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gjour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Gmois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Gannee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Grue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gboite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GcodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gpays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        GpaysResidence.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Belgique", "Afghanistan", "Afrique du Sud", "Albanie", "Algérie", "Allemagne", "Andorre", "Angola", "Anguilla", "Antarctique", "Antigua-et-Barbuda", "Antilles néerlandaises", "Arabie saoudite", "Argentine", "Arménie", "Aruba", "Australie", "Autriche", "Azerbaïdjan", "Bénin", "Bahamas", "Bahreïn", "Bangladesh", "Barbade", "Belau", "Belize", "Bermudes", "Bhoutan", "Biélorussie", "Birmanie", "Bolivie", "Bosnie-Herzégovine", "Botswana", "Brésil", "Brunei", "Bulgarie", "Burkina Faso", "Burundi", "Côte d'Ivoire", "Cambodge", "Cameroun", "Canada", "Cap-Vert", "Chili", "Chine", "Chypre", "Colombie", "Comores", "Congo", "Corée du Nord", "Corée du Sud", "Costa Rica", "Croatie", "Cuba", "Danemark", "Djibouti", "Dominique", "Égypte", "Émirats arabes unis", "Équateur", "Érythrée", "Estonie", "États-Unis", "Éthiopie", "Finlande", "Géorgie", "Gabon", "Gambie", "Ghana", "Gibraltar", "Grèce", "Grenade", "Groenland", "Guadeloupe", "Guam", "Guatemala", "Guinée", "Guinée équatoriale", "Guinée-Bissao", "Guyana", "Guyane française", "Haïti", "Honduras", "Hong Kong", "Hongrie", "Ile Bouvet", "Ile Christmas", "Ile Norfolk", "Iles Cayman", "Iles Cook", "Iles Féroé", "Iles Falkland", "Iles Fidji", "Iles Géorgie du Sud et Sandwich du Sud", "Iles Heard et McDonald", "Iles Marshall", "Iles Pitcairn", "Iles Salomon", "Iles Svalbard et Jan Mayen", "Iles Turks-et-Caicos", "Iles Vierges américaines", "Iles Vierges britanniques", "Iles des Cocos (Keeling)", "Iles mineures éloignées des États-Unis", "Inde", "Indonésie", "Iran", "Iraq", "Irlande", "Islande", "Israël", "Italie", "Jamaïque", "Japon", "Jordanie", "Kazakhstan", "Kenya", "Kirghizistan", "Kiribati", "Koweït", "Laos", "Lesotho", "Lettonie", "Liban", "Liberia", "Libye", "Liechtenstein", "Lituanie", "Luxembourg", "Macao", "Madagascar", "Malaisie", "Malawi", "Maldives", "Mali", "Malte", "Mariannes du Nord", "Maroc", "Martinique", "Maurice", "Mauritanie", "Mayotte", "Mexique", "Micronésie", "Moldavie", "Monaco", "Mongolie", "Montserrat", "Mozambique", "Népal", "Namibie", "Nauru", "Nicaragua", "Niger", "Nigeria", "Nioué", "Norvège", "Nouvelle-Calédonie", "Nouvelle-Zélande", "Oman", "Ouganda", "Ouzbékistan", "Pérou", "Pakistan", "Panama", "Papouasie-Nouvelle-Guinée", "Paraguay", "Pays-Bas", "Philippines", "Pologne", "Polynésie française", "Porto Rico", "Portugal", "Qatar", "République centrafricaine", "République démocratique du Congo", "République dominicaine", "République tchèque", "Réunion", "Roumanie", "Royaume-Uni", "Russie", "Rwanda", "Sénégal", "Sahara occidental", "Saint-Christophe-et-Niévès", "Saint-Marin", "Saint-Pierre-et-Miquelon", "Saint-Siège", "Saint-Vincent-et-les-Grenadines", "Sainte-Hélène", "Sainte-Lucie", "Salvador", "Samoa", "Samoa américaines", "Sao Tomé-et-Principe", "Seychelles", "Sierra Leone", "Singapour", "Slovénie", "Slovaquie", "Somalie", "Soudan", "Sri Lanka", "Suède", "Suisse", "Suriname", "Swaziland", "Syrie", "Taïwan", "Tadjikistan", "Tanzanie", "Tchad", "Terres australes françaises", "Territoire britannique de l'Océan Indien", "Thaïlande", "Timor Oriental", "Togo", "Tokélaou", "Tonga", "Trinité-et-Tobago", "Tunisie", "Turkménistan", "Turquie", "Tuvalu", "Ukraine", "Uruguay", "Vanuatu", "Venezuela", "Viêt Nam", "Wallis-et-Futuna", "Yémen", "Yougoslavie", "Zambie", "Zimbabwe" }));

        jLabel30.setText("Pays");

        jLabel31.setText("Ville");

        jLabel32.setText("Code Postal");

        jLabel33.setText("Boite");

        jLabel34.setText("Numéro");

        jLabel35.setText("Rue");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Si votre adresse légale est différente de");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("l'adresse où vous résidez, merci d'indiquer");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("votre adresse de résidence (kot ou autre)");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("ci-dessous :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(GrueResidence)
                        .addComponent(GpaysResidence, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GvilleResidence, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)
                        .addComponent(jLabel31)
                        .addComponent(jLabel30)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(GnumeroResidence, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GboiteResidence, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel33)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GcodePostalResidence, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel32))))
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrueResidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GnumeroResidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GboiteResidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GcodePostalResidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GvilleResidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GpaysResidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Page: ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("1");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("/");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("6");

        Bterminer.setText("Terminer");
        Bterminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BterminerActionPerformed(evt);
            }
        });

        Bannuler.setText("Annuler");
        Bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BannulerActionPerformed(evt);
            }
        });

        Bsuivant.setText("Suivant");
        Bsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsuivantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bannuler, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bterminer, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(Bsuivant, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(Bannuler)
                    .addComponent(Bterminer)
                    .addComponent(Bsuivant))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 0, 51));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Identité");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 760, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsuivantActionPerformed
        if(checkChamps()){
            enregistrerData();
            parent.changeState(Main.NOUVEAU_VOLONTAIREP2);
        }
    }//GEN-LAST:event_BsuivantActionPerformed

    private void BterminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BterminerActionPerformed
        if(checkChamps()){
            enregistrerData();
            boolean cont = false;
            volontaire = parent.getVolontaire();
            PacketCom packet = new PacketCom(States.NOUVEAU_VOLONTAIRE, (Object)volontaire);
            socket.send(packet);
            try {
                PacketCom packetReponse = socket.receive();
                String type = packetReponse.getType();
                if(type.equals(States.NOUVEAU_VOLONTAIRE_OUI)){
                    parent.afficherMessage("Ajout nouveau volontaire réussi.");
                    cont = true;
                }else if(type.equals(States.NOUVEAU_VOLONTAIRE_NON)){
                    String message = (String) packetReponse.getObjet();
                    parent.afficherMessage(message);
                }
            } catch (Exception ex) {
                Logger.getLogger(Wizard_Nouveau.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(cont){
                parent.changeState(Main.LOGGED);
            }
        }
    }//GEN-LAST:event_BterminerActionPerformed

    private void GfemmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GfemmeActionPerformed
        if(Gfemme.isSelected()){
            GnomFille.setEnabled(true);
        }else{
            GnomFille.setEnabled(false);
        }
    }//GEN-LAST:event_GfemmeActionPerformed

    private void BannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BannulerActionPerformed
        parent.changeState(Main.LOGGED);
    }//GEN-LAST:event_BannulerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bannuler;
    private javax.swing.JButton Bsuivant;
    private javax.swing.JButton Bterminer;
    private javax.swing.JComboBox Gannee;
    private javax.swing.JTextField Gboite;
    private javax.swing.JTextField GboiteResidence;
    private javax.swing.JTextField GcodePostal;
    private javax.swing.JTextField GcodePostalResidence;
    private javax.swing.JTextField Gemail;
    private javax.swing.JRadioButton Gfemme;
    private javax.swing.JRadioButton Ghomme;
    private javax.swing.JComboBox Gjour;
    private javax.swing.JComboBox Gmois;
    private javax.swing.JTextField Gnom;
    private javax.swing.JTextField GnomFille;
    private javax.swing.JTextField Gnumero;
    private javax.swing.JTextField GnumeroResidence;
    private javax.swing.JComboBox Gpays;
    private javax.swing.JComboBox GpaysResidence;
    private javax.swing.JTextField Gprenom;
    private javax.swing.JTextField Grue;
    private javax.swing.JTextField GrueResidence;
    private javax.swing.JTextField Gville;
    private javax.swing.JTextField GvilleResidence;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    private void ComboBoxAnnee() {
        for(int i=1997; i>=1920; i--){
            Gannee.addItem(i);
        }
    }

    private void fillChampIdentite() {
        Gnom.setText(volontaire.getIdentite().getNom());
        Gprenom.setText(volontaire.getIdentite().getPrenom());
        if(volontaire.getIdentite().getSexe() == "M"){
            Ghomme.setSelected(true);
        }else{
            Gfemme.setSelected(true);
        }
        GnomFille.setText(volontaire.getIdentite().getNomJeuneFille());
        String dateNaissance = new SimpleDateFormat("dd/MM/yyyy").format(volontaire.getIdentite().getDateNaissance());
        String[] split = dateNaissance.split("/");
        int jour = Integer.parseInt(split[0]);
        int mois = Integer.parseInt(split[1]);
        int annee = Integer.parseInt(split[2]);
        Gjour.setSelectedIndex(jour-1);
        Gmois.setSelectedIndex(mois-1);

        boolean found = false;
        for(int i=0; i<Gannee.getItemCount() && !found; i++){
            if(Integer.parseInt(Gannee.getItemAt(i).toString()) == annee){
                Gannee.setSelectedIndex(i);
            }
        }
    }

    private void fillChampAdresse() {
        Gemail.setText(volontaire.getAdresse().getEmail());
        Grue.setText(volontaire.getAdresse().getRue());
        //Gnumero.setText((volontaire.getAdresse().getNuméro() == -1 ? "" : ""+volontaire.getAdresse().getNuméro()));
        Gboite.setText(volontaire.getAdresse().getBoite());
        //GcodePostal.setText((volontaire.getAdresse().getCodePostal() == -1 ? "" : ""+volontaire.getAdresse().getCodePostal()));
        Gville.setText(volontaire.getAdresse().getVille());

        boolean found = false;
        for(int i=0; i<Gpays.getItemCount() && !found; i++){
            if(Gpays.getItemAt(i).toString().equalsIgnoreCase(volontaire.getAdresse().getPays())){
                Gpays.setSelectedIndex(i);
                found = true;
            }
        }
    }

    private void fillChampResidence() {
        GrueResidence.setText(volontaire.getResidence().getRue());
        //GnumeroResidence.setText((volontaire.getResidence().getNuméro() == -1 ? "" : ""+volontaire.getResidence().getNuméro()));
        GboiteResidence.setText(volontaire.getResidence().getBoite());
        //GcodePostalResidence.setText((volontaire.getResidence().getCodePostal() == -1 ? "" : ""+volontaire.getResidence().getCodePostal()));
        GvilleResidence.setText(volontaire.getResidence().getVille());

        boolean found = false;
        for(int i=0; i<GpaysResidence.getItemCount() && !found; i++){
            if(GpaysResidence.getItemAt(i).toString().equalsIgnoreCase(volontaire.getResidence().getPays())){
                GpaysResidence.setSelectedIndex(i);
                found = true;
            }
        }
    }

    private void enregistrerData() {
        Identite identite = new Identite();
            if(matricule != null){
                identite.setMatricule(matricule);
            }else{
                identite.setMatricule(Gnom.getText() + " " + Gprenom.getText());
            }
            identite.setNom(Gnom.getText());
            identite.setPrenom(Gprenom.getText());
            identite.setSexe((Ghomme.isSelected() ? "h" : "f"));
            identite.setNomJeuneFille(GnomFille.getText());

            String jour = Gjour.getSelectedItem().toString();
            String mois = Gmois.getSelectedItem().toString();
            String annee = Gannee.getSelectedItem().toString();
            String dateString = jour + "/" + mois + "/" + annee;
            Date dateNaissance = null;
            try {
                dateNaissance = new SimpleDateFormat("dd/MM/yyyy").parse(dateString);
            } catch (ParseException ex) {
                Logger.getLogger(M_NouveauVolontaireP1.class.getName()).log(Level.SEVERE, null, ex);
            }

            identite.setDateNaissance(dateNaissance);

        Adresse adresse = new Adresse();
            adresse.setEmail(Gemail.getText());

            adresse.setRue(Grue.getText());
            //adresse.setNuméro(Integer.parseInt(Gnumero.getText()));
            try{
                adresse.setBoite(Gboite.getText());
            }catch(Exception ex){

            }
            //adresse.setCodePostal(Integer.parseInt(GcodePostal.getText()));
            adresse.setVille(Gville.getText());
            adresse.setPays(Gpays.getSelectedItem().toString());

        Residence residence = new Residence();
            residence.setRue(GrueResidence.getText());
            try{
                //residence.setNuméro(Integer.parseInt(GnumeroResidence.getText()));
            }catch(Exception ex){

            }
            try{
                residence.setBoite(GboiteResidence.getText());
            }catch(Exception ex){

            }
            try{
                //residence.setCodePostal(Integer.parseInt(GcodePostalResidence.getText()));
            }catch(Exception ex){

            }
            residence.setVille(GvilleResidence.getText());
            residence.setPays((GpaysResidence.getSelectedItem().toString().equals(" ") ? "" : GpaysResidence.getSelectedItem().toString()));


        parent.setVolontaireP1(identite, adresse, residence);
    }

    private boolean checkChamps() {
        if(!checkLabelString(Gnom)){
            parent.afficherMessage("Veuillez rentrer un nom valide");
            return false;
        }else if(!checkLabelString(Gprenom)){
            parent.afficherMessage("Veuillez rentrer un prenom valide");
            return false;
        }else if(!checkLabelEmail(Gemail)){
            parent.afficherMessage("Veuillez rentrer un email valide");
            return false;
        }else if(!checkLabelString(Grue)){
            parent.afficherMessage("Veuillez rentrer une rue valide");
            return false;
        }else if(!checkLabelInt(Gnumero)){
            parent.afficherMessage("Veuillez rentrer un numéro valide");
            return false;
        }else if(!checkLabelInt(GcodePostal)){
            parent.afficherMessage("Veuillez rentrer un code postal valide");
            return false;
        }else if(!checkLabelString(Gville)){
            parent.afficherMessage("Veuillez rentrer une ville valide");
            return false;
        }
        return true;
    }

    private boolean checkLabelString(JTextField champ) {
        if(champ.getText() == null || champ.getText().isEmpty()){
            return false;
        }else{
            return true;
        }
    }

    private boolean checkLabelEmail(JTextField champ) {
        if(champ.getText() == null || champ.getText().isEmpty()){
            return false;
        }else{
            return true;
        }
    }

    private boolean checkLabelInt(JTextField champ) {
        if(champ.getText() == null || champ.getText().isEmpty()){
            return false;
        }else{
            try{
                Integer.parseInt(champ.getText());
                return true;
            }catch(Exception ex){
                return false;
            }
        }
    }
}
