/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NouveauVolontaire;

import Containers.Complementaire;
import Containers.Volontaire;
import GUI.Panels.Main;
import Network.NetworkClient;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Greenlamp
 */
public class M_NouveauVolontaireP4 extends javax.swing.JPanel {

    /**
     * Creates new form M_NouveauVolontaire1
     */
    Main parent = null;
    NetworkClient socket = null;
    Volontaire volontaire = null;

    public M_NouveauVolontaireP4(Main parent, NetworkClient socket) {
        initComponents();
        this.socket = socket;
        this.parent = parent;
        ComboBoxAnnee();
        volontaire = parent.getVolontaire();
        if(volontaire.getComplementaire() != null){
            fillChampComplementaire();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GactivitePro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        G1 = new javax.swing.JCheckBox();
        G2 = new javax.swing.JCheckBox();
        G3 = new javax.swing.JCheckBox();
        G4 = new javax.swing.JCheckBox();
        G5 = new javax.swing.JCheckBox();
        G6 = new javax.swing.JCheckBox();
        Gprecision = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        GlangueMaternelle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        GautreLangue1 = new javax.swing.JTextField();
        GautreLangue2 = new javax.swing.JTextField();
        GautreLangue3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Gdiplome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Gpermis = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        Gcategorie = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Gjour = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        Gmois = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        Gannee = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        GselectionMedicale = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        GdateValidite = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nouveau volontaire");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(1130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Renseignements complémentaires");

        jLabel2.setText("Activité professionnelle que vous exercez ou avez exercé à titre principal");

        jLabel3.setText("Actuellement vous êtes");

        G1.setBackground(new java.awt.Color(153, 153, 153));
        G1.setText("au travail");

        G2.setBackground(new java.awt.Color(153, 153, 153));
        G2.setText("aux études");

        G3.setBackground(new java.awt.Color(153, 153, 153));
        G3.setText("en recherche d'emploi");

        G4.setBackground(new java.awt.Color(153, 153, 153));
        G4.setText("à la retraite ou assimilé");

        G5.setBackground(new java.awt.Color(153, 153, 153));
        G5.setText("au foyer");

        G6.setBackground(new java.awt.Color(153, 153, 153));
        G6.setText("autre, précisez:");

        jLabel4.setText("Langue maternelle");

        jLabel5.setText("Autre(s) langue(s) couramment parlée(s)");

        jLabel6.setText("Qualification ou diplôme");

        jLabel7.setText("Permis de conduire");

        Gpermis.setBackground(new java.awt.Color(153, 153, 153));
        Gpermis.setText("Oui");

        jLabel8.setText("Précisez la catégorie");

        jLabel9.setText("Obtenu le");

        Gjour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel10.setText("/");

        Gmois.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel11.setText("/");

        jLabel12.setText("Sélection médicale");

        GselectionMedicale.setBackground(new java.awt.Color(153, 153, 153));
        GselectionMedicale.setText("Oui");

        jLabel13.setText("Précisez la date de validité");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GlangueMaternelle)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(G6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gprecision))
                    .addComponent(GautreLangue1)
                    .addComponent(GautreLangue2)
                    .addComponent(GautreLangue3)
                    .addComponent(Gdiplome)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(G4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(G5))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(G1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(G2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(G3))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel40)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GactivitePro))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Gpermis))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Gcategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Gjour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Gmois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Gannee, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GselectionMedicale))
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(GdateValidite))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GactivitePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G1)
                    .addComponent(G2)
                    .addComponent(G3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G4)
                    .addComponent(G5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G6)
                    .addComponent(Gprecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GlangueMaternelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GautreLangue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GautreLangue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GautreLangue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gdiplome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Gpermis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Gcategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Gjour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Gmois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Gannee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(GselectionMedicale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GdateValidite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Page: ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("4");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("/");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("6");

        jButton2.setText("Terminer");

        jButton3.setText("Annuler");

        jButton4.setText("Suivant");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Précédent");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Complementaire complementaire = new Complementaire();
            complementaire.setActivitePro(GactivitePro.getText());
            if(G1.isSelected()){
                complementaire.addActivite(G1.getText());
            }
            if(G2.isSelected()){
                complementaire.addActivite(G2.getText());
            }
            if(G3.isSelected()){
                complementaire.addActivite(G3.getText());
            }
            if(G4.isSelected()){
                complementaire.addActivite(G4.getText());
            }
            if(G5.isSelected()){
                complementaire.addActivite(G5.getText());
            }
            if(G6.isSelected()){
                complementaire.addActivite(Gprecision.getText());
            }
            complementaire.setLangueMaternelle(GlangueMaternelle.getText());
            complementaire.addLangue(GautreLangue1.getText());
            complementaire.addLangue(GautreLangue2.getText());
            complementaire.addLangue(GautreLangue3.getText());
            complementaire.setQualification(Gdiplome.getText());
            if(Gpermis.isSelected()){
                complementaire.setPermis(true);
            }
            complementaire.setCategorie(Gcategorie.getText());

            String jour = Gjour.getSelectedItem().toString();
            String mois = Gmois.getSelectedItem().toString();
            String annee = Gannee.getSelectedItem().toString();
            String dateString = jour + "/" + mois + "/" + annee;
            Date dateObtention = null;
            try {
                dateObtention = new SimpleDateFormat("dd/MM/yyyy").parse(dateString);
            } catch (ParseException ex) {
                Logger.getLogger(M_NouveauVolontaireP1.class.getName()).log(Level.SEVERE, null, ex);
            }
            complementaire.setDateObtention(dateObtention);
            if(GselectionMedicale.isSelected()){
                complementaire.setSelectionMedicale(true);
            }
            complementaire.setDateValidité(GdateValidite.getText());

        parent.setVolontaireP4(complementaire);
        parent.changeState(Main.NOUVEAU_VOLONTAIREP5);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Complementaire complementaire = new Complementaire();
            complementaire.setActivitePro(GactivitePro.getText());
            if(G1.isSelected()){
                complementaire.addActivite(G1.getText());
            }
            if(G2.isSelected()){
                complementaire.addActivite(G2.getText());
            }
            if(G3.isSelected()){
                complementaire.addActivite(G3.getText());
            }
            if(G4.isSelected()){
                complementaire.addActivite(G4.getText());
            }
            if(G5.isSelected()){
                complementaire.addActivite(G5.getText());
            }
            if(G6.isSelected()){
                complementaire.addActivite(Gprecision.getText());
            }
            complementaire.setLangueMaternelle(GlangueMaternelle.getText());
            complementaire.addLangue(GautreLangue1.getText());
            complementaire.addLangue(GautreLangue2.getText());
            complementaire.addLangue(GautreLangue3.getText());
            complementaire.setQualification(Gdiplome.getText());
            if(Gpermis.isSelected()){
                complementaire.setPermis(true);
            }
            complementaire.setCategorie(Gcategorie.getText());

            String jour = Gjour.getSelectedItem().toString();
            String mois = Gmois.getSelectedItem().toString();
            String annee = Gannee.getSelectedItem().toString();
            String dateString = jour + "/" + mois + "/" + annee;
            Date dateObtention = null;
            try {
                dateObtention = new SimpleDateFormat("dd/MM/yyyy").parse(dateString);
            } catch (ParseException ex) {
                Logger.getLogger(M_NouveauVolontaireP1.class.getName()).log(Level.SEVERE, null, ex);
            }
            complementaire.setDateObtention(dateObtention);
            if(GselectionMedicale.isSelected()){
                complementaire.setSelectionMedicale(true);
            }
            complementaire.setDateValidité(GdateValidite.getText());

        parent.setVolontaireP4(complementaire);
        parent.changeState(Main.NOUVEAU_VOLONTAIREP3);
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox G1;
    private javax.swing.JCheckBox G2;
    private javax.swing.JCheckBox G3;
    private javax.swing.JCheckBox G4;
    private javax.swing.JCheckBox G5;
    private javax.swing.JCheckBox G6;
    private javax.swing.JTextField GactivitePro;
    private javax.swing.JComboBox Gannee;
    private javax.swing.JTextField GautreLangue1;
    private javax.swing.JTextField GautreLangue2;
    private javax.swing.JTextField GautreLangue3;
    private javax.swing.JTextField Gcategorie;
    private javax.swing.JTextField GdateValidite;
    private javax.swing.JTextField Gdiplome;
    private javax.swing.JComboBox Gjour;
    private javax.swing.JTextField GlangueMaternelle;
    private javax.swing.JComboBox Gmois;
    private javax.swing.JCheckBox Gpermis;
    private javax.swing.JTextField Gprecision;
    private javax.swing.JCheckBox GselectionMedicale;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    private void fillChampComplementaire() {
        GactivitePro.setText(volontaire.getComplementaire().getActivitePro());
        if(volontaire.getComplementaire().getListeActivite().contains(G1.getText())){
            G1.setSelected(true);
            volontaire.getComplementaire().getListeActivite().remove(G1.getText());
        }
        if(volontaire.getComplementaire().getListeActivite().contains(G2.getText())){
            G2.setSelected(true);
            volontaire.getComplementaire().getListeActivite().remove(G2.getText());
        }
        if(volontaire.getComplementaire().getListeActivite().contains(G3.getText())){
            G3.setSelected(true);
            volontaire.getComplementaire().getListeActivite().remove(G3.getText());
        }
        if(volontaire.getComplementaire().getListeActivite().contains(G4.getText())){
            G4.setSelected(true);
            volontaire.getComplementaire().getListeActivite().remove(G4.getText());
        }
        if(volontaire.getComplementaire().getListeActivite().contains(G5.getText())){
            G5.setSelected(true);
            volontaire.getComplementaire().getListeActivite().remove(G5.getText());
        }
        try{
            Gprecision.setText(volontaire.getComplementaire().getListeActivite().getFirst());
            G6.setSelected(true);
        }catch(Exception ex){

        }
        GlangueMaternelle.setText(volontaire.getComplementaire().getLangueMaternelle());
        if(volontaire.getComplementaire().getListeLangue().size() >= 1){
            GautreLangue1.setText(volontaire.getComplementaire().getListeLangue().get(0));
        }
        if(volontaire.getComplementaire().getListeLangue().size() >= 2){
            GautreLangue1.setText(volontaire.getComplementaire().getListeLangue().get(1));
        }
        if(volontaire.getComplementaire().getListeLangue().size() >= 3){
            GautreLangue1.setText(volontaire.getComplementaire().getListeLangue().get(2));
        }
        Gdiplome.setText(volontaire.getComplementaire().getQualification());
        if(volontaire.getComplementaire().isPermis()){
            Gpermis.setSelected(true);
        }
        Gcategorie.setText(volontaire.getComplementaire().getCategorie());

        String dateObtention = new SimpleDateFormat("dd/MM/yyyy").format(volontaire.getComplementaire().getDateObtention());
        String[] split = dateObtention.split("/");
        int jour = Integer.parseInt(split[0]);
        int mois = Integer.parseInt(split[1]);
        int annee = Integer.parseInt(split[2]);
        Gjour.setSelectedIndex(jour-1);
        Gmois.setSelectedIndex(mois-1);

        boolean found = false;
        for(int i=0; i<Gannee.getItemCount() && !found; i++){
            if(Integer.parseInt(Gannee.getItemAt(i).toString()) == annee){
                Gannee.setSelectedIndex(i);
            }
        }

        if(volontaire.getComplementaire().isSelectionMedicale()){
            GselectionMedicale.setSelected(true);
        }
        GdateValidite.setText(volontaire.getComplementaire().getDateValidité());
    }
    private void ComboBoxAnnee() {
        for(int i=1997; i>=1920; i--){
            Gannee.addItem(i);
        }
    }

}
