/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

import Helpers.SwingUtils;
import SSL.NetworkClientSSL;
import States.States;
import java.util.LinkedList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import my.cr.PacketCom.PacketCom;

/**
 *
 * @author Greenlamp
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    Main parent = null;
    NetworkClientSSL socket = null;

    public Menu() {
        initComponents();
    }

    Menu(Main parent, NetworkClientSSL socket) {
        initComponents();
        this.socket = socket;
        this.parent = parent;
        cacherInterdit();
        //fillBidon();
        getAnniversaires();
        getBrevetsExpire();
        getHorairesNonComplet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BnouveauVolontaire = new javax.swing.JButton();
        Bgrilles = new javax.swing.JButton();
        Bdroits = new javax.swing.JButton();
        Bgroupes = new javax.swing.JButton();
        Busers = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Bcache = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Bvehicule = new javax.swing.JButton();
        Blieux = new javax.swing.JButton();
        panelBrev = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Gbrevet = new javax.swing.JTable();
        panelAnniv = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ganniv = new javax.swing.JTable();
        panelGrille = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ggrille = new javax.swing.JTable();
        Gbanniere = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<html><p>Consulter</p> <p>volontaires</p></html>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BnouveauVolontaire.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BnouveauVolontaire.setText("<html><p>Nouveau</p> <p>volontaire</p></html>");
        BnouveauVolontaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnouveauVolontaireActionPerformed(evt);
            }
        });

        Bgrilles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bgrilles.setText("<html><p>Gérer</p> <p>grilles</p> <p>horaires</p></html>");
        Bgrilles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgrillesActionPerformed(evt);
            }
        });

        Bdroits.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bdroits.setText("Droits");
        Bdroits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdroitsActionPerformed(evt);
            }
        });

        Bgroupes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bgroupes.setText("Groupes");
        Bgroupes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgroupesActionPerformed(evt);
            }
        });

        Busers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Busers.setText("Utilisateurs");
        Busers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusersActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Déconnexion");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        Bcache.setText("vider cache");
        Bcache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcacheActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Menu");

        Bvehicule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bvehicule.setText("<html><p>Gestion</p> <p>véhicules</p></html>");
        Bvehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvehiculeActionPerformed(evt);
            }
        });

        Blieux.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Blieux.setText("<html><p>Gestion</p> <p>Lieux</p></html>");
        Blieux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlieuxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BnouveauVolontaire)
                                    .addComponent(Bcache, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bgrilles, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Bdroits, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bgroupes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Busers, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Bvehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Blieux, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bgrilles, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Bcache)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BnouveauVolontaire, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bdroits, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bgroupes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Busers, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bvehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Blieux, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBrev.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Brevet(s) Expiré dans le mois:");

        Gbrevet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Brevet", "Date d'expiration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Gbrevet);

        javax.swing.GroupLayout panelBrevLayout = new javax.swing.GroupLayout(panelBrev);
        panelBrev.setLayout(panelBrevLayout);
        panelBrevLayout.setHorizontalGroup(
            panelBrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrevLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBrevLayout.setVerticalGroup(
            panelBrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAnniv.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Anniversaire(s) de la semaine:");

        Ganniv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Date de naissance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Ganniv);

        javax.swing.GroupLayout panelAnnivLayout = new javax.swing.GroupLayout(panelAnniv);
        panelAnniv.setLayout(panelAnnivLayout);
        panelAnnivLayout.setHorizontalGroup(
            panelAnnivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnivLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnnivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnnivLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAnnivLayout.setVerticalGroup(
            panelAnnivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnivLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelGrille.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Grille(s) Horaire non complète:");

        Ggrille.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom véhicule", "Nom départ", "Numero semaine", "Date debut", "Date fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Ggrille);

        javax.swing.GroupLayout panelGrilleLayout = new javax.swing.GroupLayout(panelGrille);
        panelGrille.setLayout(panelGrilleLayout);
        panelGrilleLayout.setHorizontalGroup(
            panelGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrilleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGrilleLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        panelGrilleLayout.setVerticalGroup(
            panelGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrilleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        Gbanniere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banniere.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAnniv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelGrille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Gbanniere)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelAnniv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBrev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gbanniere, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BnouveauVolontaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnouveauVolontaireActionPerformed
        parent.changeState(Main.NOUVEAU_VOLONTAIRE);
    }//GEN-LAST:event_BnouveauVolontaireActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        parent.changeState(Main.CONSULTATION);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BgrillesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgrillesActionPerformed
        parent.changeState(Main.GESTION_GRILLES_HORAIRES);
    }//GEN-LAST:event_BgrillesActionPerformed

    private void BdroitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdroitsActionPerformed
        parent.changeState(Main.GESTION_DROITS);
    }//GEN-LAST:event_BdroitsActionPerformed

    private void BgroupesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgroupesActionPerformed
        parent.changeState(Main.GESTION_GROUPES);
    }//GEN-LAST:event_BgroupesActionPerformed

    private void BusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusersActionPerformed
        parent.changeState(Main.GESTION_UTILISATEURS);
    }//GEN-LAST:event_BusersActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        parent.disconnect();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void BcacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcacheActionPerformed
        parent.cleanBackup();
    }//GEN-LAST:event_BcacheActionPerformed

    private void BvehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvehiculeActionPerformed
        parent.changeState(Main.GESTION_VEHICULES);
    }//GEN-LAST:event_BvehiculeActionPerformed

    private void BlieuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlieuxActionPerformed
        parent.changeState(Main.GESTION_LIEUX);
    }//GEN-LAST:event_BlieuxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcache;
    private javax.swing.JButton Bdroits;
    private javax.swing.JButton Bgrilles;
    private javax.swing.JButton Bgroupes;
    private javax.swing.JButton Blieux;
    private javax.swing.JButton BnouveauVolontaire;
    private javax.swing.JButton Busers;
    private javax.swing.JButton Bvehicule;
    private javax.swing.JTable Ganniv;
    private javax.swing.JLabel Gbanniere;
    private javax.swing.JTable Gbrevet;
    private javax.swing.JTable Ggrille;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelAnniv;
    private javax.swing.JPanel panelBrev;
    private javax.swing.JPanel panelGrille;
    // End of variables declaration//GEN-END:variables

    private void fillBidon() {
        String[] tuple = {"Dupré", "Marc", "Brevet de secourisme", "12/06/2013"};
        String[] tuple2 = {"Shoryu", "jin", "Ambulancier TMS", "27/05/2013"};
        String[] tuple3 = {"Nocil", "jonathan", "Brevet Européen de Premiers Secours", "21/05/2013"};

        String[] anniv = {"Knuts", "Gabriel", "16/05/1991"};

        String[] grille = {"112", "Liege 2", "22", "01/06/2013", "08/06/2013"};

        Vector vector = new Vector();
        vector.add(tuple[0]);
        vector.add(tuple[1]);
        vector.add(tuple[2]);
        vector.add(tuple[3]);
        SwingUtils.addToTable(Gbrevet, vector);

        vector = new Vector();
        vector.add(tuple2[0]);
        vector.add(tuple2[1]);
        vector.add(tuple2[2]);
        vector.add(tuple2[3]);
        SwingUtils.addToTable(Gbrevet, vector);

        vector = new Vector();
        vector.add(tuple3[0]);
        vector.add(tuple3[1]);
        vector.add(tuple3[2]);
        vector.add(tuple3[3]);
        SwingUtils.addToTable(Gbrevet, vector);

        vector = new Vector();
        vector.add(anniv[0]);
        vector.add(anniv[1]);
        vector.add(anniv[2]);
        SwingUtils.addToTable(Ganniv, vector);

        vector = new Vector();
        vector.add(grille[0]);
        vector.add(grille[1]);
        vector.add(grille[2]);
        vector.add(grille[3]);
        vector.add(grille[4]);
        SwingUtils.addToTable(Ggrille, vector);


    }

    private void cacherInterdit() {
        LinkedList<String> droits = parent.getDroits();

        if(!droits.contains("CREATE_VOLUNTEER")){
            BnouveauVolontaire.setEnabled(false);
            Bcache.setEnabled(false);
        }else{
            BnouveauVolontaire.setEnabled(true);
            Bcache.setEnabled(true);
        }

        if(!droits.contains("SEE_MANAGE_RIGHTS")){
            Bdroits.setEnabled(false);
        }else{
            Bdroits.setEnabled(true);
        }

        if(!droits.contains("SEE_MANAGE_GROUP")){
            Bgroupes.setEnabled(false);
        }else{
            Bgroupes.setEnabled(true);
        }

        if(!droits.contains("SEE_MANAGE_USER")){
            Busers.setEnabled(false);
        }else{
            Busers.setEnabled(true);
        }

        if(!droits.contains("SEE_HORAIRE")){
            Bgrilles.setEnabled(false);
        }else{
            Bgrilles.setEnabled(true);
        }

        if(!droits.contains("SEE_LIEU")){
            Blieux.setEnabled(false);
        }else{
            Blieux.setEnabled(true);
        }

        if(!droits.contains("SEE_VEHICULE")){
            Bvehicule.setEnabled(false);
        }else{
            Bvehicule.setEnabled(true);
        }

        if(!droits.contains("SEE_BIRTHDAY")){
            panelAnniv.setVisible(false);
        }else{
            panelAnniv.setVisible(true);
        }

        if(!droits.contains("SEE_EXP_BREVET")){
            panelBrev.setVisible(false);
        }else{
            panelBrev.setVisible(true);
        }

        if(!droits.contains("SEE_HORAIRE_MISS")){
            panelGrille.setVisible(false);
        }else{
            panelGrille.setVisible(true);
        }
    }

    private void getAnniversaires() {
        if(parent.getDroits().contains("SEE_BIRTHDAY")){
            PacketCom packet = new PacketCom(States.GET_BIRTHDAY, null);
            socket.send(packet);
            try {
                PacketCom retour = socket.receive();
                traitementBirthday(retour);
            } catch (Exception ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void getBrevetsExpire() {
        if(parent.getDroits().contains("SEE_EXP_BREVET")){
            PacketCom packet = new PacketCom(States.GET_EXP_BREVET, null);
            socket.send(packet);
            try {
                PacketCom retour = socket.receive();
                traitementExpBrevet(retour);
            } catch (Exception ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void getHorairesNonComplet() {
        if(parent.getDroits().contains("SEE_HORAIRE_MISS")){
            PacketCom packet = new PacketCom(States.GET_HORAIRE_MISS, null);
            socket.send(packet);
            try {
                PacketCom retour = socket.receive();
                traitementHoraireMiss(retour);
            } catch (Exception ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void traitementBirthday(PacketCom retour) {
        String type = retour.getType();
        if(type.equals(States.GET_BIRTHDAY_OUI)){
            LinkedList<Object[]> listeBirthday = (LinkedList<Object[]>) retour.getObjet();
            SwingUtils.emptyTable(Ganniv);
            SwingUtils.addToTable(Ganniv, listeBirthday);
        }else{
            String message = (String)retour.getObjet();
            parent.afficherMessage(message);
        }
    }

    private void traitementExpBrevet(PacketCom retour) {
        String type = retour.getType();
        if(type.equals(States.GET_EXP_BREVET_OUI)){
            LinkedList<Object[]> listeBrevet = (LinkedList<Object[]>) retour.getObjet();
            SwingUtils.emptyTable(Gbrevet);
            SwingUtils.addToTable(Gbrevet, listeBrevet);
        }else{
            String message = (String)retour.getObjet();
            parent.afficherMessage(message);
        }
    }

    private void traitementHoraireMiss(PacketCom retour) {
        String type = retour.getType();
        if(type.equals(States.GET_HORAIRE_MISS_OUI)){
            LinkedList<Object[]> listeGrille = (LinkedList<Object[]>) retour.getObjet();
            SwingUtils.emptyTable(Ggrille);
            SwingUtils.addToTable(Ggrille, listeGrille);
        }else{
            String message = (String)retour.getObjet();
            parent.afficherMessage(message);
        }
    }
}
